export type BoardItem = {
  id: string;
  title: string;
  description: string;
  repo: "sportin-pro" | "sportin-pro-mobile" | "rork-sportin-io";
  platform: "web" | "ios" | "android" | "backend" | "all";
  type: "feature" | "tech-debt" | "security" | "architecture" | "bug";
  priority: "critical" | "high" | "medium" | "low";
  status: "backlog" | "todo" | "in-progress" | "done";
  source?: string;
};

export type ColumnId = BoardItem["status"];

export const COLUMNS: { id: ColumnId; label: string }[] = [
  { id: "backlog", label: "Backlog" },
  { id: "todo", label: "To Do" },
  { id: "in-progress", label: "In Progress" },
  { id: "done", label: "Done" },
];

export const REPOS = ["sportin-pro", "sportin-pro-mobile", "rork-sportin-io"] as const;
export const PLATFORMS = ["web", "ios", "android", "backend", "all"] as const;
export const TYPES = ["feature", "tech-debt", "security", "architecture", "bug"] as const;
export const PRIORITIES = ["critical", "high", "medium", "low"] as const;

export const SEED_ITEMS: BoardItem[] = [
  // ── sportin-pro (Web) — Disabled features ─────────────────────────
  {
    id: "sp-clients",
    title: "Clients",
    description: "Client management dashboard. Disabled in sidebar.",
    repo: "sportin-pro",
    platform: "web",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "app/dashboard/layout.tsx",
  },
  {
    id: "sp-sessions",
    title: "Sessions",
    description: "Session scheduling & management. Disabled in sidebar.",
    repo: "sportin-pro",
    platform: "web",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "app/dashboard/layout.tsx",
  },
  {
    id: "sp-programs",
    title: "Programs",
    description: "Training programs CRUD. Disabled in sidebar.",
    repo: "sportin-pro",
    platform: "web",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "app/dashboard/layout.tsx",
  },
  {
    id: "sp-payments",
    title: "Payments",
    description: "Payment processing dashboard. Disabled in sidebar.",
    repo: "sportin-pro",
    platform: "web",
    type: "feature",
    priority: "high",
    status: "backlog",
    source: "app/dashboard/layout.tsx",
  },
  {
    id: "sp-messages",
    title: "Messages",
    description: "In-app messaging. Disabled in sidebar.",
    repo: "sportin-pro",
    platform: "web",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "app/dashboard/layout.tsx",
  },
  {
    id: "sp-reviews",
    title: "Reviews",
    description: "Review system for clubs/trainers. Disabled in sidebar.",
    repo: "sportin-pro",
    platform: "web",
    type: "feature",
    priority: "low",
    status: "backlog",
    source: "app/dashboard/layout.tsx",
  },
  {
    id: "sp-reports",
    title: "Reports",
    description: "Analytics & reporting dashboard. Disabled in sidebar.",
    repo: "sportin-pro",
    platform: "web",
    type: "feature",
    priority: "low",
    status: "backlog",
    source: "app/dashboard/layout.tsx",
  },
  {
    id: "sp-schedule-crud",
    title: "Schedule CRUD",
    description: "Create, read, update, delete class schedules.",
    repo: "sportin-pro",
    platform: "web",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "README.md",
  },
  {
    id: "sp-member-roster",
    title: "Member roster + add/remove",
    description: "Manage club members: invite, add, remove.",
    repo: "sportin-pro",
    platform: "web",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "README.md",
  },
  {
    id: "sp-trainer-mgmt",
    title: "Trainer management",
    description: "Manage trainers assigned to a club.",
    repo: "sportin-pro",
    platform: "web",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "README.md",
  },
  {
    id: "sp-branding-editor",
    title: "Branding editor",
    description: "Logo and color customization for clubs.",
    repo: "sportin-pro",
    platform: "web",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "README.md",
  },
  {
    id: "sp-custom-domains",
    title: "Custom domain wiring",
    description: "Vercel Domains API integration for white-label clubs.",
    repo: "sportin-pro",
    platform: "web",
    type: "feature",
    priority: "low",
    status: "backlog",
    source: "README.md",
  },
  {
    id: "sp-stripe-connect",
    title: "Stripe Connect",
    description: "Gym → member subscription payments via Stripe Connect.",
    repo: "sportin-pro",
    platform: "backend",
    type: "feature",
    priority: "high",
    status: "backlog",
    source: "README.md",
  },
  {
    id: "sp-stripe-billing",
    title: "Stripe Billing",
    description: "Gym → SportIn Pro SaaS subscription via Stripe Billing.",
    repo: "sportin-pro",
    platform: "backend",
    type: "feature",
    priority: "high",
    status: "backlog",
    source: "README.md",
  },

  // ── sportin-pro-mobile — All specs, 0% built ─────────────────────
  {
    id: "mob-auth",
    title: "Auth + onboarding",
    description: "Sign up, log in, magic link for mobile apps.",
    repo: "sportin-pro-mobile",
    platform: "all",
    type: "feature",
    priority: "high",
    status: "backlog",
    source: "specs/0001-auth-and-onboarding.md",
  },
  {
    id: "mob-schedule",
    title: "Class schedule view",
    description: "Browse and view class schedules.",
    repo: "sportin-pro-mobile",
    platform: "all",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "specs/0002-class-schedule.md",
  },
  {
    id: "mob-booking",
    title: "Booking flow",
    description: "Book, cancel, and join waitlist for classes.",
    repo: "sportin-pro-mobile",
    platform: "all",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "specs/0003-booking-flow.md",
  },
  {
    id: "mob-branding",
    title: "Tenant branding",
    description: "Load gym logo + colors from the gym record at launch.",
    repo: "sportin-pro-mobile",
    platform: "all",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "specs/0004-tenant-branding.md",
  },
  {
    id: "mob-trainer",
    title: "Trainer view",
    description: "Trainer schedule and roster view.",
    repo: "sportin-pro-mobile",
    platform: "all",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "specs/0005-trainer-view.md",
  },
  {
    id: "mob-profile",
    title: "Member profile",
    description: "Member profile screen.",
    repo: "sportin-pro-mobile",
    platform: "all",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "README.md",
  },
  {
    id: "mob-push",
    title: "Push notifications",
    description: "Push notification infrastructure for mobile.",
    repo: "sportin-pro-mobile",
    platform: "all",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "README.md",
  },
  {
    id: "mob-offline",
    title: "Offline-first cache",
    description: "Offline caching layer for mobile apps.",
    repo: "sportin-pro-mobile",
    platform: "all",
    type: "feature",
    priority: "low",
    status: "backlog",
    source: "README.md",
  },
  {
    id: "mob-whitelabel",
    title: "White-label native shell",
    description: "Per-tenant Bundle ID + assets via Fastlane.",
    repo: "sportin-pro-mobile",
    platform: "all",
    type: "feature",
    priority: "low",
    status: "backlog",
    source: "README.md",
  },

  // ── rork-sportin-io — CRITICAL security ───────────────────────────
  {
    id: "rork-sec-profiles-rls",
    title: "Profiles admin RLS vulnerability",
    description: "USING(true) WITH CHECK(true) — any authenticated user can update any other user's profile.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "security",
    priority: "critical",
    status: "backlog",
    source: "db_improvements.md (0-A)",
  },
  {
    id: "rork-sec-steps-exposed",
    title: "step_snapshots publicly readable",
    description: "34K raw fitness rows exposed to all authenticated users via public SELECT.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "security",
    priority: "critical",
    status: "backlog",
    source: "db_improvements.md (0-B)",
  },
  {
    id: "rork-sec-puma-rls",
    title: "puma_turtle_history missing RLS policies",
    description: "RLS enabled with zero policies — users cannot read their own award history.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "security",
    priority: "high",
    status: "backlog",
    source: "db_improvements.md (0-C)",
  },
  {
    id: "rork-sec-definer",
    title: "SECURITY DEFINER functions lack search_path",
    description: "4 functions (handle_new_profile, search_users_safe, book_football_position, register_for_marathon_category) vulnerable to schema injection.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "security",
    priority: "high",
    status: "backlog",
    source: "db_improvements.md (0-D)",
  },
  {
    id: "rork-sec-webhook",
    title: "spike-webhook: no signature verification",
    description: "Accepts any POST without verification — attacker can set any user's step_source.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "security",
    priority: "critical",
    status: "backlog",
    source: "PLAN.md (0.1)",
  },
  {
    id: "rork-sec-push-auth",
    title: "push-notify/push-scheduled: no caller auth",
    description: "Unauthorized caller can trigger notifications to entire user base.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "security",
    priority: "critical",
    status: "backlog",
    source: "PLAN.md (0.2)",
  },

  // ── rork-sportin-io — Bugs ────────────────────────────────────────
  {
    id: "rork-bug-like-count",
    title: "Like/comment counters never decrement",
    description: "Triggers only handle INSERT, not DELETE — counters drift permanently upward.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "bug",
    priority: "high",
    status: "backlog",
    source: "db_improvements.md (1-A)",
  },
  {
    id: "rork-bug-dupe-likes",
    title: "Duplicate likes possible",
    description: "No UNIQUE(post_id, user_id) constraint on feed_likes.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "bug",
    priority: "high",
    status: "backlog",
    source: "db_improvements.md (1-B)",
  },
  {
    id: "rork-bug-missing-fn",
    title: "reevaluate_yesterday_for_all broken",
    description: "Calls a function that does not exist — crashes on invocation.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "bug",
    priority: "high",
    status: "backlog",
    source: "db_improvements.md (1-C)",
  },

  // ── rork-sportin-io — Tech debt ───────────────────────────────────
  {
    id: "rork-td-dupe-idx",
    title: "Duplicate indexes",
    description: "Unnecessary write overhead from duplicate indexes.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "tech-debt",
    priority: "medium",
    status: "backlog",
    source: "db_improvements.md (1-D)",
  },
  {
    id: "rork-td-steps-migration",
    title: "step_snapshots migration incomplete",
    description: "step_snapshots → daily_step_snapshots dual-write drift.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "tech-debt",
    priority: "medium",
    status: "backlog",
    source: "db_improvements.md (2-A)",
  },
  {
    id: "rork-td-push-churn",
    title: "push_preferences churn",
    description: "361 inserts for 4 rows — re-inserts on every launch.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "tech-debt",
    priority: "medium",
    status: "backlog",
    source: "db_improvements.md (2-B)",
  },
  {
    id: "rork-td-route-text",
    title: "route_data stored as TEXT",
    description: "Should be JSONB for validation; currently TEXT with no server-side checks.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "tech-debt",
    priority: "medium",
    status: "backlog",
    source: "db_improvements.md (2-C)",
  },
  {
    id: "rork-td-schema-export",
    title: "Live schema not exported to repo",
    description: "Schema drift invisible — no diffable source of truth.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "tech-debt",
    priority: "medium",
    status: "backlog",
    source: "db_improvements.md (3-A)",
  },
  {
    id: "rork-td-scoring-dupe",
    title: "Puma/turtle scoring logic duplicated 4x",
    description: "Scoring logic copy-pasted across 4 locations.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "tech-debt",
    priority: "medium",
    status: "backlog",
    source: "db_improvements.md (3-B)",
  },
  {
    id: "rork-td-profiles-god",
    title: "profiles god table needs splitting",
    description: "Split identity, push state, step state, rewards into separate tables.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "architecture",
    priority: "low",
    status: "backlog",
    source: "db_improvements.md (3-C)",
  },

  // ── rork-sportin-io — Architecture refactor ───────────────────────
  {
    id: "rork-arch-di",
    title: "DI Foundation",
    description: "Create AppDependencies container, define 8 core protocols, inject into all ViewModels. 152 .shared call sites to eliminate.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "architecture",
    priority: "high",
    status: "backlog",
    source: "PLAN.md Phase 1",
  },
  {
    id: "rork-arch-split-supa",
    title: "Split SupabaseService",
    description: "1,190 lines, 40+ methods across 8 domains. Extract into Auth/Profile/Feed/Activity/Leaderboard/Sync/Config repositories.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "architecture",
    priority: "high",
    status: "backlog",
    source: "PLAN.md Phase 2",
  },
  {
    id: "rork-arch-network-views",
    title: "Remove network calls from Views",
    description: "137 direct service calls across 43 view files — all should go through ViewModels.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "architecture",
    priority: "medium",
    status: "backlog",
    source: "PLAN.md Phase 3",
  },
  {
    id: "rork-arch-concurrency",
    title: "Concurrency hygiene",
    description: "66 unguarded Task blocks, 74 @MainActor annotations, Task.detached usage to clean up.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "architecture",
    priority: "medium",
    status: "backlog",
    source: "PLAN.md Phase 4",
  },
  {
    id: "rork-arch-steps-ssot",
    title: "Steps/Run SSOT",
    description: "Dual tracking pipelines (WorkoutViewModel + RunTracker), HealthKitManager calling LiveActivityManager.shared directly.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "architecture",
    priority: "medium",
    status: "backlog",
    source: "PLAN.md Phase 5",
  },
  {
    id: "rork-arch-errors",
    title: "Error handling system",
    description: "37 try? usages, 313 print() calls (target: 0), no typed error system.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "architecture",
    priority: "medium",
    status: "backlog",
    source: "PLAN.md Phase 6",
  },
  {
    id: "rork-arch-tests",
    title: "Test harness",
    description: "Zero automated tests. Need mocks and tests for 4 critical flows.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "architecture",
    priority: "high",
    status: "backlog",
    source: "PLAN.md Phase 7",
  },
  {
    id: "rork-arch-nav",
    title: "Navigation refactor",
    description: "Mixed navigation: boolean state, custom offset sheets, NavigationLink inside sheets.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "architecture",
    priority: "medium",
    status: "backlog",
    source: "PLAN.md Phase 8",
  },

  // ── rork-sportin-io — File size splits ────────────────────────────
  {
    id: "rork-td-split-supa",
    title: "Split SupabaseService.swift (1190 lines)",
    description: "Way over the 200-line limit. Priority: high.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "tech-debt",
    priority: "high",
    status: "backlog",
    source: "file-size-refactor/tasks.md",
  },
  {
    id: "rork-td-split-feed-vm",
    title: "Split FeedViewModel.swift (613 lines)",
    description: "Over 200-line limit. Priority: high.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "tech-debt",
    priority: "high",
    status: "backlog",
    source: "file-size-refactor/tasks.md",
  },
  {
    id: "rork-td-split-feed-view",
    title: "Split FeedView.swift (574 lines)",
    description: "Over 200-line limit. Priority: high.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "tech-debt",
    priority: "high",
    status: "backlog",
    source: "file-size-refactor/tasks.md",
  },
  {
    id: "rork-td-split-profile",
    title: "Split ProfileView.swift (750 lines)",
    description: "Over 200-line limit. Priority: medium.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "tech-debt",
    priority: "medium",
    status: "backlog",
    source: "file-size-refactor/tasks.md",
  },
  {
    id: "rork-td-split-hk",
    title: "Split HealthKitManager.swift (517 lines)",
    description: "Over 200-line limit. Priority: medium.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "tech-debt",
    priority: "medium",
    status: "backlog",
    source: "file-size-refactor/tasks.md",
  },

  // ── rork-sportin-io — Feature TODOs ───────────────────────────────
  {
    id: "rork-feat-moderation",
    title: "ModerationService",
    description: "Content moderation service not yet on dev. Referenced in FeedView and ReportContentSheet.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "FeedView.swift, FeedViewModel.swift",
  },
  {
    id: "rork-feat-notif-svc",
    title: "NotificationService",
    description: "Notification service not yet on dev. Referenced in FeedView.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "FeedView.swift",
  },
  {
    id: "rork-feat-rewards-nav",
    title: "Rewards navigation wiring",
    description: "Multiple TODOs: BrandRewardDetailView, ChallengeDetailView, AllChallengesForBrandView, ActivityHistoryView links not wired.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "Views/Rewards/*.swift",
  },
  {
    id: "rork-feat-step-validation",
    title: "Server-side step validation",
    description: "Anti-cheat: validate_step_sync Supabase function needed.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "feature",
    priority: "high",
    status: "backlog",
    source: "specs/server-side-step-validation",
  },
  {
    id: "rork-feat-garmin",
    title: "Garmin integration",
    description: "Garmin wearable integration. 7 incomplete test tasks.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "specs/garmin-spike-integration",
  },
  {
    id: "rork-feat-workout-post",
    title: "Workout auto-post",
    description: "Share panel + route map snapshot. 5 incomplete test tasks.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "feature",
    priority: "medium",
    status: "backlog",
    source: "specs/workout-auto-post",
  },
  {
    id: "rork-feat-email-notif",
    title: "Email notifications",
    description: "Email notification preferences — profiles column doesn't exist yet.",
    repo: "rork-sportin-io",
    platform: "backend",
    type: "feature",
    priority: "low",
    status: "backlog",
    source: "NotificationsSettingsView.swift",
  },
  {
    id: "rork-td-mapbox",
    title: "Mapbox 11 migration",
    description: "Migrate Replay3DMapView to Mapbox v11.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "tech-debt",
    priority: "low",
    status: "backlog",
    source: "Replay3DMapView.swift",
  },
  {
    id: "rork-td-hardcoded-creds",
    title: "Remove hardcoded credentials",
    description: "Fallback Supabase URL and anon key hardcoded in source.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "security",
    priority: "high",
    status: "backlog",
    source: "PLAN.md Phase 2 (2.9)",
  },
  {
    id: "rork-td-zero-tests",
    title: "Zero automated tests",
    description: "0 automated tests across the entire iOS app.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "tech-debt",
    priority: "high",
    status: "backlog",
    source: "PLAN.md Phase 7",
  },
  {
    id: "rork-feat-android-profile-vm",
    title: "Android: move target history to ViewModel",
    description: "Target history fetching currently in wrong layer.",
    repo: "rork-sportin-io",
    platform: "android",
    type: "tech-debt",
    priority: "medium",
    status: "backlog",
    source: "ProfileViewModel.kt:25",
  },
  {
    id: "rork-feat-bg-location",
    title: "Background location for workouts",
    description: "Currently foreground-only — GPS data lost when phone is pocketed.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "feature",
    priority: "high",
    status: "backlog",
    source: "permissions-audit.md",
  },
  {
    id: "rork-feat-weekly-share-bug",
    title: "Weekly share card heatmap blank",
    description: "DailyHeatmapShareCard hour data returns empty — renders blank.",
    repo: "rork-sportin-io",
    platform: "ios",
    type: "bug",
    priority: "medium",
    status: "backlog",
    source: "specs/weekly-share-card",
  },
];
